# Generated by Django 5.1.6 on 2025-04-29 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgethink", "0002_alter_budget_category_alter_budget_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="budget",
            name="budgethink__user_id_438c5a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category")},
        ),
        migrations.AlterField(
            model_name="budget",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
