# Generated by Django 5.1.6 on 2025-04-30 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgethink", "0003_remove_budget_budgethink__user_id_438c5a_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budget",
            name="month",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="budget",
            name="year",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="budgethink.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "category", "month", "year")},
        ),
    ]
